name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Flutter action
      uses: subosito/flutter-action@v1.1.1
      with:
       # The Flutter version to make available on the path
        # The Flutter build release channel
        channel: stable
        # Deprecated. Use flutter-version instead. Will not be supported after October 1, 2019
